Fix NPU tensor rebuild requires_grad load
Co-authored-by: zhenyu10<shizhenyu5@huawei.com>



# message auto-generated for no-merge-commit merge:
!37817 merge master-storage-requires-grad-fix into master

Fix NPU tensor rebuild requires_grad load

Created-by: zhenyu10
Commit-by: zhenyu10
Merged-by: ascend-robot
Description: <!--
PR描述模板更新日期：20260203
-->

# 【合入来源】
> <font color="red">**如有社区issue，请关联issue链接**</font>\
> <font color="red">**请勿携带内部流程信息（需求链接、问题单、内部issue等）**</font>

- [ ] 需求
- [x] 问题单
- [x] issue/工单
- [ ] 重构优化
- [ ] 资料更新

关联issue: https://gitcode.com/Ascend/pytorch/issues/2297

# 【修改方案】
> 请描述修改内容的具体实现，涉及哪些组件之间进行交互，可以用1、2、3、...进行罗列\
> 如果是需求或者重构类的PR，需要补充详细设计文档（说明上下游组件关系、时序图、类图、DFX能力等内容）

报错场景：
1. checkpoint 里保存的是 NPU tensor
2. 这个 NPU tensor 序列化时带着 requires_grad=True
3. 加载时走到 torch_npu.utils.storage._rebuild_npu_tensor
4. 旧代码先创建 requires_grad=True 的临时 leaf tensor
5.  然后对它执行 set_ 这种 in-place 操作
报错：
RuntimeError: a leaf Variable that requires grad is being used in an in-place operation.

修改方式：对齐torch原生社区，empty里不使用requires_grad=True

# 【资料变更】
> 请确认是否涉及资料变更。如涉及，需要在PR中体现，并简要说明修改内容。如不涉及，需填写“不涉及”

不涉及

# 【接口变更】
> 请确认是否涉及跨代码仓或者客户面可见的接口变更。如涉及，需要详细说明接口以及对应的变更内容，同时需要在资料中体现。如不涉及，需填写“不涉及”

不涉及

# 【功能验证】
> 说明测试场景，测试方法。如果本次测试方式与常规单元测试不同，请详细说明您的测试步骤\
> 新增/变更内容是否已新增/适配UT测试用例看护，并补充测试自验证截图

可以正常加载权重，验证见issue

# 【CheckList】
> PR提交人对以下CheckList自检项进行全量自检，自检通过或不涉及，均修改 [ ] 为 [x]

- [x] 代码注释完备，正确记录错误日志
- [x] 代码实现进行了返回值、空指针等校验
- [x] PR标题正确使用类型标签，如：feat、fix、refactor、docs、test等
- [x] PR持续集成流水线（CI）执行通过，代码检查无异常


See merge request: Ascend/pytorch!37817