fix inductor bug
Co-authored-by: kkjocker<hexuanyu1@huawei.com>



# message auto-generated for no-merge-commit merge:
!29183 merge master_cifix into master

fix inductor bug

Created-by: kkjocker
Commit-by: kkjocker
Merged-by: ascend-robot
Description: <!--  Thanks for sending a pull request! 
-->

**What type of PR is this?**
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespaces from that line:
>
> /kind bug
> /kind task
> /kind feature


**What does this PR do / why do we need it**:


**Which issue(s) this PR fixes**:
<!-- 
*Automatically closes linked issue when PR is merged.
Usage: `Fixes #<issue number>`, or `Fixes (paste link of issue)`.
-->
Fixes ImportError: cannot import name 'triton_dtype' from 'torch._inductor.utils'

**Special notes for your reviewers**:




See merge request: Ascend/pytorch!29183